update github, workflow

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -1,45 +1,42 @@
 name: NextJS Build Check
 
 on:
-  push:
-    branches: [ main ]
-  pull_request:
-    branches: [ main ]
+    push:
+        branches: [main]
+    pull_request:
+        branches: [main]
 
 jobs:
-  build:
-    runs-on: ubuntu-latest
-    env: 
-      CI: true
+    build:
+        runs-on: ubuntu-latest
+        env:
+            CI: true
 
-    steps:
-    - uses: actions/checkout@v4
+        steps:
+            - uses: actions/checkout@v4
 
-    - name: Setup environemnt
-      run: cp .env.ci .env
+            - name: Use Node.js
+              uses: actions/setup-node@v3
+              with:
+                  node-version: "20"
 
-    - name: Use Node.js
-      uses: actions/setup-node@v3
-      with:
-        node-version: '20'
+            - name: Setup Bun
+              uses: oven-sh/setup-bun@v1
+              with:
+                  bun-version: latest
 
-    - name: Setup Bun
-      uses: oven-sh/setup-bun@v1
-      with:
-        bun-version: latest
+            - name: Install dependencies
+              run: bun install
 
-    - name: Install dependencies
-      run: bun install
+            - name: Build NextJS application
+              run: bun run build
 
-    - name: Build NextJS application
-      run: bun run build
-
-    - name: Check build status
-      run: |
-        if [ $? -eq 0 ]; then
-          echo "NextJS build successful"
-          exit 0
-        else
-          echo "NextJS build failed"
-          exit 1
-        fi
+            - name: Check build status
+              run: |
+                  if [ $? -eq 0 ]; then
+                    echo "NextJS build successful"
+                    exit 0
+                  else
+                    echo "NextJS build failed"
+                    exit 1
+                  fi
